version: 2
project_name: px-go

before:
  hooks:
    - go test ./...

builds:
  - id: px
    main: ./cmd/px
    binary: px-go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/BlackDark/px-go/internal/version.Version={{ .Version }} -X github.com/BlackDark/px-go/internal/version.Commit={{ .Commit }} -X github.com/BlackDark/px-go/internal/version.Date={{ .Date }}

  - id: px-windows-console
    main: ./cmd/px
    binary: px-go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/BlackDark/px-go/internal/version.Version={{ .Version }} -X github.com/BlackDark/px-go/internal/version.Commit={{ .Commit }} -X github.com/BlackDark/px-go/internal/version.Date={{ .Date }}

  - id: px-windows-headless
    main: ./cmd/px
    binary: pxw-go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -H=windowsgui -X github.com/BlackDark/px-go/internal/version.Version={{ .Version }} -X github.com/BlackDark/px-go/internal/version.Commit={{ .Commit }} -X github.com/BlackDark/px-go/internal/version.Date={{ .Date }}

archives:
  - id: unix
    ids: [px]
    formats: [tar.gz]
  - id: windows
    ids: [px-windows-console, px-windows-headless]
    formats: [zip]

checksum:
  name_template: checksums.txt

release:
  draft: false
  prerelease: auto

dockers:
  - ids: [px]
    use: buildx
    dockerfile: docker/Dockerfile.goreleaser
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
    image_templates:
      - ghcr.io/blackdark/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/blackdark/{{ .ProjectName }}:latest-amd64
  - ids: [px]
    use: buildx
    dockerfile: docker/Dockerfile.goreleaser
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
    image_templates:
      - ghcr.io/blackdark/{{ .ProjectName }}:{{ .Version }}-arm64
      - ghcr.io/blackdark/{{ .ProjectName }}:latest-arm64

docker_manifests:
  - name_template: ghcr.io/blackdark/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/blackdark/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/blackdark/{{ .ProjectName }}:{{ .Version }}-arm64
  - name_template: ghcr.io/blackdark/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/blackdark/{{ .ProjectName }}:latest-amd64
      - ghcr.io/blackdark/{{ .ProjectName }}:latest-arm64
