[proxy]

; NTLM server(s) to connect through. IP:port, hostname:port
;   Multiple proxies can be specified comma separated. Px will iterate through
;   and use the one that works
server =

; PAC file to use to connect
;   Use in place of --server if PAC file should be loaded from a URL or local
;   file. Relative paths will be relative to the Px script or binary
pac =

; PAC file encoding
;   Specify in case default 'utf-8' encoding does not work
; pac_encoding =

; Network interface(s) to listen on. Comma separated, default: 127.0.0.1
;   --gateway and --hostonly override this to bind to all interfaces
listen = 127.0.0.1

; Port to run this proxy on - default: 3128
port = 3128

; Allow remote machines to use proxy. 0 or 1, default: 0
;   Overrides --listen and binds to all interfaces
gateway = 0

; Allow only local interfaces to use proxy. 0 or 1, default: 0
;   Px allows all IP addresses assigned to local interfaces to use the service.
;   This allows local apps as well as VM or container apps to use Px when in a
;   NAT config. Overrides --listen and overrides the default --allow rules
hostonly = 0

; Allow connection from specific subnets. Comma separated, default: *.*.*.*
;   127.0.0.1 - specific ip
;   192.168.0.* - wildcards
;   192.168.0.1-192.168.0.255 - ranges
;   192.168.0.1/24 - CIDR
allow = *.*.*.*

; Direct connect to specific subnets or domains like a regular proxy. Comma separated
;   Skip the NTLM proxy for connections to these hosts
noproxy =

; Override or send User-Agent header on client's behalf
useragent =

; Authentication to use when SSPI is unavailable. Format is domain\username
username =

; Force instead of discovering upstream proxy type
auth =

; Enable Kerberos ticket management. 0 or 1, default: 0
kerberos = 0

[client]

; Client authentication username. Format is domain\username
client_username =

; Enable authentication for client connections. Comma separated, default: NONE
client_auth = NONE

; Disable SSPI for client authentication on Windows. default: 0
client_nosspi = 0

[settings]

; Number of parallel workers (processes). Valid integer, default: 1
workers = 1

; Thread pool size for upstream proxy connections. Valid integer, default: 32
threads = 32

; Idle timeout in seconds for HTTP connect sessions. Valid integer, default: 30
idle = 30

; Timeout in seconds for connections before giving up. Valid float, default: 20
socktimeout = 20.0

; Time interval in seconds before refreshing proxy info. Valid int, default: 60
proxyreload = 60

; Run in foreground. 0 or 1, default: 0
foreground = 0

; Logging output. 0=none, 1=script dir, 2=cwd, 3=unique, 4=stdout
log = 0
